##########################################################
# Dockerfile to run a flask-based web application
# Based on an image_base:1.0 image
# Please name the image to lib_image_base:1.0 image
##########################################################

# Set the base image to use to centos
FROM image_base:1.0

# Set the file maintainer
MAINTAINER Wang Bobo,wbb392797665@sina.com

# install python3 dependencies
RUN pip3 install  -i https://mirrors.aliyun.com/pypi/simple/ flask gunicorn gevent numpy sklearn tensorflow matplotlib





























































